### ISSUE TITLE
Different ECN marking on a contiguous range of packets

### ISSUE THREAD

**Issue by goelvidhi** [marten-seemann/draft-seemann-quic-accurate-ack-ecn#1]
As I was saying on the email list, it may be possible that the receiver receives a mix of CE and ECT packets which it may not ACK immediately due to more frequent CE marking in case of L4S.

The below field and the ACK_RANGES field assumes that ECN Marking will be same for all the packets from smallest to largest in that block. This may not be true. Probably a solution is create a new ACK Range for whenever the ECT value changes even if there is no gap.
```
First ACK Range {
  ACK Range Length (i),
  ECN Marking (8),
}
```

**Comment by marten-seemann** [comment]
Yes, that was exactly the intention of this draft! As soon as the ECN marking changes, you need to create a new ACK range.

any suggestion how to make this clearer?

**Comment by goelvidhi** [comment]
This issue has been resolved in latest draft.
