### ISSUE TITLE
Add motivation for the draft

### ISSUE THREAD

**Issue by goelvidhi** [marten-seemann/draft-seemann-quic-accurate-ack-ecn#6]
Basically cover two items:
1. Why knowing sequence of CE marked and non-CE marked packets is important. Coz it helps to order the AI and MD events accurately
2. Why knowing packet number for non CE marked packets is important. Coz from packet number, we can get the packet size, which gives us total number of non CE marked bytes used for AI.

**Comment by marten-seemann** [comment]
Fixed by #7.
